### ISSUE TITLE
Wrong links to the mysql_pubkey.asc file

### ISSUE THREAD

**Issue by VanTanev** [chef-cookbooks/yum-mysql-community#2]
Current links point to: `https://raw.githubusercontent.com/someara/yum-mysql-community/master/files/mysql_pubkey.asc`

Should be: `https://raw.githubusercontent.com/opscode-cookbooks/yum-mysql-community/master/files/default/mysql_pubkey.asc`

This was broken in 29b97bdad183

**Comment by runwaldarshu** [comment]
Now that repo from https://raw.githubusercontent.com/someara/yum-mysql-community/master/files/mysql_pubkey.asc is deleted this URL gives 404

**Comment by sambao21** [comment]
Is this still valid with the change from https://github.com/chef-cookbooks/yum-mysql-community/commit/afd2b419c068974ffd0df64884401e8ade675ef7?

**Comment by someara** [comment]
This was fixed last year in afd2b41 ... just updated the orgs it uses from someara to chef-cookbooks here b6be352fdf1d7db3f06ce6df491906a31b64f09
