### ISSUE TITLE
Response: Field 'metadata.maintainer' invalid

### ISSUE THREAD

**Issue by nellshamrell** [chef-cookbooks/yum-mysql-community#8]
I'm getting this error when trying to upload this cookbook to a Chef Server using berkshelf

Uploading yum-mysql-community [0.1.21]
ERROR: The data in your request was invalid
Response: Field 'metadata.maintainer' invalid

**Comment by someara** [comment]
That's pretty bizarre... 

It's pretty standard looking: https://github.com/chef-cookbooks/yum-mysql-community/blob/master/metadata.rb#L2

Do you have the same problem with say, yum-centos? https://github.com/chef-cookbooks/yum-centos/blob/master/metadata.rb#L2

**Comment by nellshamrell** [comment]
Apologies, looks like that error message was misleading, the problem is not within this cookbook.  Closing the issue!
